---
# tasks file for redmine
- name: Disable ruby gem documentation
  lineinfile:
    dest: /usr/local/etc/gemrc
    line: "{{ 'gem:' + ' --no-ri --no-rdoc' }}"
    create: yes
    state: present

- name: install ruby gems
  gem:
    name: "{{ item }}"
    user_install: no
  with_items:
    - bundler

- name: install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - imagemagick
    - libmagickwand-dev
    - nginx
    - libpq-dev
    - thin

- name: Create redmine user
  user:
    name: redmine
    home: "{{ redmine_dir }}"
    createhome: no
    system: yes

- name: Enable SSH_AUTH_SOCK on sudo calls
  copy:
    src: ssh_auth_sock
    dest: /etc/sudoers.d/ssh_auth_sock
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: 0440

- name: Get redmine
  git:
    repo: "{{ redmine_repo }}"
    accept_hostkey: yes
    ssh_opts: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    dest: "{{ redmine_dir }}"
    version: "{{ redmine_version }}"

- name: Ensure redmine permissions
  file:
    path: "{{ redmine_dir }}"
    owner: redmine
    group: redmine
    recurse: yes
    state: directory

- name: Upload database configuration
  template:
    src: database.psql.yml
    dest: "{{ redmine_dir }}/config/database.yml"
    owner: redmine
    group: redmine

- name: Upload redmine configuration
  template:
    src: redmine.config.yml
    dest: "{{ redmine_dir }}/config/configuration.yml"
    owner: redmine
    group: redmine

- name: Install dependencies
  # command: bundle install --deployment --without development test
  command: bundle install --without development test
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  # sudo_user: redmine

- name: Migrate database
  command: bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  sudo_user: redmine

- name: Generate session store secret
  command: bundle exec rake generate_secret_token
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
  sudo_user: redmine

- name: Load default dataset
  command: bundle exec rake redmine:load_default_data
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    RAILS_ENV: production
    REDMINE_LANG: en
  sudo_user: redmine

- name: Ensure thin run directory permissions
  file:
    path: /var/run/thin
    state: directory
    owner: redmine
    group: redmine

- name: Create softlink for thin server
  file:
    path: /etc/init.d/redmine
    src: /etc/init.d/thin
    state: link

- name: Upload Thin configuration
  template:
    src: thin.redmine.yml
    dest: /etc/thin1.9.1/redmine.yml
  notify: restart thin

- name: Upload nginx configuration
  template:
    src: nginx.redmine.j2
    dest: /etc/nginx/sites-available/redmine

- name: Enable redmine configuration on nginx
  file:
    src: /etc/nginx/sites-available/redmine
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx
