######################################
# Redmine configuration
######################################

######################################
# SMTP server using TLS (Mandrill)
######################################
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.mandrillapp.com"
      port: 587
      domain: "{{ mandrillapp_domain }}"
      authentication: :plain
      user_name: "{{ mandrillapp_username }}"
      password: "{{ mandrillapp_password }}"
